services:
  backend:
    build:
      context: ./backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      PGURI: postgres://postgres:Frieri@database/postgres
    ports:
      - "3000:3000"

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Frieri
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
